name: PR Comment Hello

on:
  issue_comment:
    types: [created]

jobs:
  say-hello:
    if: github.event.issue.pull_request != null && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Print hello
        run: echo "hello"
