name: TestPR

on:
  issue_comment:
    types: [created]

jobs:
  helo:
    runs-on: ubuntu-24.04
    steps:
      - name: Show event JSON
        run: |
          echo "Event path: $GITHUB_EVENT_PATH"
          cat $GITHUB_EVENT_PATH
          echo "--- Environment ---"
          env | sort