name: PR Comment Hello

on:
  issue_comment:
    types: [created]

jobs:
  say-hello:
    if: github.event.issue.pull_request != null  # Ensure it's a PR, not an issue
    runs-on: ubuntu-latest
    steps:
      - name: Print hello
        run: echo "hello"
