name: Build

on:
  pull_request:

jobs:
  build-api:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Image Tag Env
        run: echo "PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven Packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Save Docker Image Files
        run: |
          docker pull ubuntu
          docker pull alpine
          docker tag ubuntu localhost:5000/streamshub/console-operator:${{ env.PROJECT_VERSION }}
          docker tag alpine localhost:5000/streamshub/console-operator-catalog:${{ env.PROJECT_VERSION }}
          docker images
          docker save -o console-operator-${{ env.PROJECT_VERSION }}.tar localhost:5000/streamshub/console-operator:${{ env.PROJECT_VERSION }}
          docker save -o console-operator-catalog-${{ env.PROJECT_VERSION }}.tar localhost:5000/streamshub/console-operator-catalog:${{ env.PROJECT_VERSION }}

      - name: Archive UI Image file
        uses: actions/upload-artifact@v4
        with:
          name: operator-images
          path: |
            console-operator-${{ env.PROJECT_VERSION }}.tar
            console-operator-catalog-${{ env.PROJECT_VERSION }}.tar

  build-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  call-minikube-deployment:
    uses: ./.github/workflows/minikube-deployment.yml
    needs:
      - build-api
      - build-ui