name: Run System Tests
permissions:
  contents: read

on:
  issue_comment:
    types: [created]

jobs:
  parse-and-run:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/systemtest') }}
    runs-on: ubuntu-24.04

    steps:

      - name: Set Up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'adopt'
